<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-MQ7POIOU" failures="1" tests="4" name="EdgeTest" time="29.493" errors="0" timestamp="2023-08-01T17:52:07 IST">
  <testcase classname="testClasses.LogIn" name="verifyLoginPage" time="20.951"/>
  <testcase classname="testClasses.LogIn" name="verifyCurrentUrl" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [https://saucelabs.com/] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://saucelabs.com/] but found [https://www.saucedemo.com/]
at testClasses.LogIn.verifyCurrentUrl(LogIn.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verifyCurrentUrl -->
  <testcase classname="testClasses.LogIn" name="verifyProductsPage" time="0.0">
    <skipped/>
  </testcase> <!-- verifyProductsPage -->
  <testcase classname="testClasses.LogIn" name="verifyPriceDynamically" time="0.0">
    <skipped/>
  </testcase> <!-- verifyPriceDynamically -->
</testsuite> <!-- EdgeTest -->
